name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qpdf poppler-utils tesseract-ocr ghostscript

      - name: Install Python dependencies and package
        run: |
          python -m pip install --upgrade pip setuptools wheel pytest
          pip install -e .

      - name: Run test suite
        run: |
          python -m pytest -q
